CREATE DATABASE IF NOT EXISTS pi23_projetospesqext;
USE pi23_projetospesqext;
CREATE TABLE IF NOT EXISTS area(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS categoria(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS status(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS docente(
matricula VARCHAR(07) PRIMARY KEY NOT NULL,
nome VARCHAR(200) NOT NULL,
cpf VARCHAR(11) NOT NULL,
email VARCHAR(200) NOT NULL,
telefone VARCHAR(11) NOT NULL,
senha VARCHAR (08) NOT NULL
);
CREATE TABLE IF NOT EXISTS projeto(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
titulo VARCHAR(300) NOT NULL,
descricao CHAR NOT NULL,
matricula_docente VARCHAR(07) NOT NULL,
id_status INT NOT NULL,
id_area INT NOT NULL,
id_categoria INT NOT NULL,
FOREIGN KEY (matricula_docente) REFERENCES docente(matricula),
FOREIGN KEY (id_status) REFERENCES status(id),
FOREIGN KEY (id_area) REFERENCES area(id),
FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);
CREATE TABLE IF NOT EXISTS projeto_docente(
id_projeto INT NOT NULL,
matricula_docente VARCHAR(07),
FOREIGN KEY (id_projeto) REFERENCES projeto(id),
FOREIGN KEY (matricula_docente) REFERENCES docente(matricula)
);